version: "3"

services:

  service:
    container_name: "service"
    build:
      context: Service
      dockerfile: Dockerfile
    ports:
      - 9080:8080
      - 65193:65193
    environment:
      - EMPLOYEE_HOST=employee:8080
      - ROLE_HOST=role:8080
      - DEPARTMENT_HOST=department:8080
    restart: on-failure
    depends_on:
      - employee
      - role
      - department

  employee:
    container_name: "employee"
    build:
      context: Employee
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_HOST=employee-database
    restart: on-failure
    depends_on:
      - employee-database

  employee-database:
    image: mongo:4.0.10
    container_name: employee-database
    env_file: .env
    restart: on-failure

  role:
    container_name: "role"
    build:
      context: Role
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_HOST=role-database
    restart: on-failure
    depends_on:
      - role-database

  role-database:
    image: mongo:4.0.10
    container_name: role-database
    env_file: .env
    restart: on-failure

  department:
    container_name: "department"
    build:
      context: Department
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_HOST=department-database
    restart: on-failure
    depends_on:
      - department-database

  department-database:
    image: mongo:4.0.10
    container_name: department-database
    env_file: .env
    restart: on-failure